CREATE TABLE IF NOT EXISTS NETLIFY_LOGS (RAW_DATA VARIANT);

CREATE TABLE IF NOT EXISTS EMAIL_DRAFTS (
    ID VARCHAR DEFAULT UUID_STRING(),
    LEAD_EMAIL VARCHAR,
    LEAD_NAME VARCHAR,
    CATEGORY VARCHAR,
    PROPENSITY_SCORE FLOAT,
    EMAIL_SUBJECT VARCHAR,
    EMAIL_BODY VARCHAR,
    STATUS VARCHAR DEFAULT 'PENDING'
);