import streamlit as st
import json
from airflow import settings
from airflow.models import Connection
from airflow.utils.session import create_session

# --- UI LAYOUT ---
st.title("⚙️ Data Ops: Agent Configuration")

st.warning("⚠️ ADMIN ACCESS ONLY: This panel configures the backend Service Account.")

st.markdown("""
    **Instructions for IT/Engineering:**
    1. Generate OAuth 2.0 credentials in Google Cloud Console.
    2. Input the JSON below to authorize the 'Marketing Agent' to access the corporate Gmail API.
    3. This will enable the Airflow DAG to draft emails automatically.
""")

# --- INPUT FORM ---
with st.form("gmail_auth_form"):
    st.subheader("Gmail API Credentials")
    
    # Option 1: Simple Paste (JSON) - easiest for demo
    creds_json = st.text_area(
        "Paste your 'credentials.json' content here:",
        help="Download this from Google Cloud Console > APIs & Services > Credentials"
    )
    
    # Option 2: Manual Entry (Alternative)
    with st.expander("Or enter manually"):
        client_id = st.text_input("Client ID")
        client_secret = st.text_input("Client Secret", type="password")
    
    submitted = st.form_submit_button("🔌 Connect Agent")

# --- BACKEND LOGIC (The "Magic") ---
if submitted:
    # Check if BOTH inputs are empty
    if not creds_json and (not client_id or not client_secret):
        st.error("❌ Please provide credentials (either JSON or Manual Entry).")
    
    else:
        try:
            # Logic: If JSON is empty, build it from the Manual Inputs
            if not creds_json:
                creds_data = {
                    "installed": {
                        "client_id": client_id,
                        "client_secret": client_secret,
                        # We inject standard Google defaults for the missing fields
                        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                        "token_uri": "https://oauth2.googleapis.com/token",
                        "redirect_uris": ["http://localhost"]
                    }
                }
            else:
                # Otherwise, parse the pasted JSON
                creds_data = json.loads(creds_json)
            
            # --- The rest is the same as before ---
            conn_id = "gmail_default"
            
            new_conn = Connection(
                conn_id=conn_id,
                conn_type='google_cloud_platform',
                description="Auto-generated by Sales Portal",
                extra=json.dumps({
                    "extra__google_cloud_platform__keyfile_dict": creds_data,
                    "scope": "https://www.googleapis.com/auth/gmail.compose"
                })
            )

            with create_session() as session:
                existing_conn = session.query(Connection).filter(Connection.conn_id == conn_id).first()
                if existing_conn:
                    session.delete(existing_conn)
                    st.info(f"♻️ Updating existing connection: {conn_id}")
                
                session.add(new_conn)
            
            st.success(f"✅ SUCCESS! Connection '{conn_id}' configured.")
            st.balloons()

        except json.JSONDecodeError:
            st.error("❌ Invalid JSON format.")
        except Exception as e:
            st.error(f"❌ System Error: {str(e)}")